services:
  fleetmanagementapi:
    build:
      context: ./fleetmanagementapi
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2-server:1521/~/fleetmanagement
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
    depends_on:
      - h2-server

  heartbeater:
    build:
      context: ./heartbeater
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2-server:1521/~/fleetmanagement
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
    deploy:  
      restart_policy:
        condition: manual

  penaltycalculator:
    build:
      context: ./penaltycalculator
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2-server:1521/~/fleetmanagement
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
    depends_on:
      - h2-server

  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo1

  zoo1:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  h2-server:
    image: oscarfonts/h2
    ports:
      - "1521:1521"
      - "81:81"
    environment:
      H2_OPTIONS: "-tcp -tcpAllowOthers -web -webAllowOthers"
    volumes:
      - h2-data:/opt/h2-data

volumes:
  h2-data: